### ISSUE TITLE
How to set minimunClusterSize?

### ISSUE THREAD

**Issue by ivanwitzke** [naderio/nativescript-google-maps-utils#4]
I have some markers that the coordenates are almost identical, but on the map the cluster doesn't group them unless there are more than 5 markers on the same place (which I believe is the default minimun value). Is there any way to change this setting?

**Comment by dxshindeo** [comment]
Having the same issue here, did you figure it out?

**Comment by dxshindeo** [comment]
Ah, found it: https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java

```
    public int getMinClusterSize() {
        return mMinClusterSize;
    }

    public void setMinClusterSize(int minClusterSize) {
        mMinClusterSize = minClusterSize;
   }
```

So in my service I call:

```
var renderer = new dis.clustering.view.DefaultClusterRenderer(app.android.context, dis.gMap, dis.cluster_manager);

renderer.onBeforeClusterItemRendered = function (item, markerOptions) {
    console.log("setup");
    markerOptions.alpha(0.8);
    markerOptions.flat(true);
    markerOptions.rotation(item.rotation);

    var icon = new Image();
    icon.imageSource = imageSource.fromResource('icon_location');
    var androidIcon = com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(icon.imageSource.android);
    markerOptions.icon(androidIcon);

};

dis.cluster_manager.setRenderer(renderer);

renderer.setMinClusterSize(1);
```

I don't get the "setup" console log, which is another story to figure out, but "setMinClusterSize" does its work :)

**Comment by naderio** [comment]
related to #5
closing unless unless a PR is proposed
