### ISSUE TITLE
IOS implementation

### ISSUE THREAD

**Issue by westlakem** [naderio/nativescript-google-maps-utils#9]
The readme says that IOS hasn't been implemented, but it also shows the IOS framework as a dependency... Can you clarify if this works on IOS?

**Comment by naderio** [comment]
@westlakem doesn't work on iOS, not possible to implement this due to native library' state ("Until GoogleMaps is a dynamic framework (when we stop supporting iOS 7.0), you need to add the library manually to your project to work around the issue")
check #2 for more information
